# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Version up
        run: |
          git config --global user.email yuuta3594@outlook.jp
          git config --global user.name YutaUra
          npm version patch -m "[patch] %s"

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
