# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .node-version
      - run: corepack enable pnpm
      - name: Install
        run: pnpm i
      - name: Build
        run: pnpm run build
      - name: Version up
        run: |
          git config --global user.email yuuta3594@gmail.com
          git config --global user.name YutaUra
          npm version patch -m "[patch] %s"
          git push

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
